### DISCUSSION TITLE
Invenio chart: image override via values-overrides.yaml not working (v0.7.0)

### DISCUSSION THREAD

**Discussion by wkaiser22** [inveniosoftware/helm-invenio#202] [General]
Hi,

Hello everyone, I'm facing the following issue: I'm trying to override the default image value for Invenio-Web, Invenio-Worker, etc. using values-overrides.yaml. However, the default value is always used instead.

web:
  image: " myImage "
  replicas: 1
  terminationGracePeriodSeconds: 60
  uwsgi:

Could I be misconfiguring something, or is this a bug in the chart?

Best regards

Wassilij Kaiser

**Comment by lindhe** [comment]
It sounds to me like you are struggling with how to use Helm. If you write the command you are running, I'll try to help you figure out what you are missing. 🙂

And please format your YAML example [as code](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) in the markdown, so it's easier to read!

**Comment by wkaiser22** [comment]
Hi,
I added the following to my values-overrides.yaml file:

```yaml
global:
  timezone: "Europe/Berlin"

image:
  registry: ghcr.io/hakor
  repository: invenio-dhbw-image
  tag: latest
  pullPolicy: Always
   pullSecrets: 
    - name: ghcr-invenio-secret
```
Now, when I run helm install, it uses my custom image as expected.
When I do it this way, my image is used during helm install.

But if I do it the way I used to, it no longer works:

```yaml
web:
  image: "Myimage..."
  replicas: 1
  terminationGracePeriodSeconds: 60
  uwsgi:
    processes: 2
    threads: 1
  extraEnvVars: []
  autoscaler:
    enabled: true
    scaler_cpu_utilization: 60
    max_web_replicas: 2
    min_web_replicas: 1
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 1
  startupProbe:
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 5
```
My image override is ignored, and the deployment always uses the default image
