### ISSUE TITLE
Allow custom configuration variables for web and worker pods

### ISSUE THREAD

**Issue by egabancho** [inveniosoftware/helm-invenio#136]
It'll be interesting to allow to have different configurations depending on the kind of deployment. 
I'm thinking, in particular, setting SENTRY_TRANSPORT = 'raven.transport.http.HTTPTransport' on the celery workers https://invenio-logging.readthedocs.io/en/latest/configuration.html.

I'm thinking something as simple as:
```
worker:
  extraEnvVars:
    - name: INVENIO_SENTRY_TRANSPORT
      value: 'raven.transport.http.HTTPTransport' 
```

And then render them as environmental variables directly on the container.
