### ISSUE TITLE
services: enable usage of subcharts

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/helm-invenio#24]
Helm supports the use of sub-charts (more isolation of components/services, easier debugging, potential usage of existing charts - less maintenance).

The folder structure would look like:
```
invenio
  - Chart.yaml
  - charts
      - message-queue
          - Chart.yaml
          - templates
          - values.yaml
      - database
          - Chart.yaml
          - templates
          - values.yaml
      - ... 
      - application (web, worker, etc.)
  - values.yaml
  ```

The specific `values` file would go to each chart (check for interdependencies...), then the global `values` file would simply "enable" them:

```yaml
message-queue:
  enabled: true
  image:
    repository: acme/rabbitmq
    tag: latest
database:
  enabled: false
```
