### ISSUE TITLE
improve labels usage

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/helm-invenio#25]
e.g.

*helpers.tpl*
```
{{/*
Common labels
*/}}

{{- define "common.labels" -}} 
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end -}}
```

*any deployment*
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-queue
  labels:
{{ include "common.labels" . | indent 4 }}
...
```
