### ISSUE TITLE
rabbitmq: persistency

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/helm-invenio#38]
The hostname field

In [here](https://github.com/inveniosoftware/helm-invenio/blob/master/invenio/templates/deployments/rabbitmq.yaml#L24) add the `hostname`

```
spec:
       hostname: rabbit-host # to keep queues persistent
       containers:
         - name: mq
            image: registry.cern.ch/docker.io/library/rabbitmq:3.8-management
```

The issue here is that every time we create a new container, RabbitMQ will create a new folder namespaced with the hostname.

2 issues:
1. no persistency after a rollover
2. the disk space is slowly filling up... until RabbitMQ will crash at some point with no disk space left

If we don't have replicas, so basically one max always, then it is pretty safe to hardcode the hostname.
