### ISSUE TITLE
add secrets for login salt and secret key

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/helm-invenio#64]
```
            - name: INVENIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: invenio-secrets
                  key: INVENIO_SECRET_KEY
            - name: INVENIO_SECURITY_LOGIN_SALT
              valueFrom:
                secretKeyRef:
                  name: invenio-secrets
                  key: INVENIO_SECURITY_LOGIN_SALT
```

And the corresponding secret creation
